ahhf: 
  dbname: cheddd4567654

mybatis:
  mapperLocations: classpath:db/mappers/*Mapper.xml
   
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
 
redis: 
  host: localhost
  port: 6379
  password: redis1234
  timeout: 5000 
  database: 0
  maxTotal: 100
  maxIdle: 10
  minIdle: 10
  maxWaitMillis: 3000
  testOnBorrow: true
  testOnReturn: false
  testWhileIdle: false
  timeBetweenEvictionRunsMillis: 3600000